name: Deploy Backend Infrastructure (Terraform)

on:
  push:
    paths:
      - 'infra/**'
  workflow_dispatch:

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    env:
      # Terraform will automatically read these environment variables
      # They match the variable names in variables.tf (TF_VAR_name)
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: ap-southeast-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.5

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra